export const nodeDataArray = [
  {
    text: "Text",
    color: "#38bdf8",
    stroke: "#38bdf8",
    figure: "Circle",
    fill: "#ffffff",
    strokeWidth: 2,
    width: 40,
    height: 40,
    textAlign: go.Spot.Center,
  },
  {
    text: "Text",
    color: "#a78bfa",
    stroke: "#a78bfa",
    figure: "Square",
    fill: "#ffffff",
    strokeWidth: 2,
    width: 40,
    height: 40,
    textAlign: go.Spot.Center,
  },
  {
    text: "Text",
    color: "#fde047",
    stroke: "#fde047",
    figure: "Ellipse",
    fill: "#ffffff",
    strokeWidth: 2,
    width: 50,
    height: 30,
    textAlign: go.Spot.Center,
  },
  {
    text: "Text",
    color: "#78716c",
    stroke: "#78716c",
    figure: "Rectangle",
    fill: "#ffffff",
    strokeWidth: 2,
    width: 40,
    height: 30,
    textAlign: go.Spot.Center,
  },
  {
    text: "Text",
    color: "#22c55e",
    stroke: "#22c55e",
    figure: "RoundedRectangle",
    fill: "#ffffff",
    strokeWidth: 2,
    width: 40,
    height: 30,
    textAlign: go.Spot.Center,
  },
];
